-- qlib-release: 2
local parentEnv = _ENV
local qEnv = setmetatable({}, { __index = parentEnv })
_ENV = qEnv

local function assertTable(value, name)
    if type(value) ~= "table" then
        error((name or "value") .. " must be a table, got " .. type(value), 3)
    end
end

local function assertString(value, name)
    if type(value) ~= "string" or value == "" then
        error((name or "value") .. " must be a non-empty string", 3)
    end
end

local function openFile(path, mode)
    local file = fs.open(path, mode)
    if not file then
        error('Unable to open "' .. path .. '" with mode "' .. mode .. '"', 3)
    end
    return file
end

local function readFile(path)
    local file = openFile(path, "r")
    local contents = file.readAll()
    file.close()
    return contents
end

local function writeFile(path, contents)
    local directory = fs.getDir(path)
    if directory ~= "" and not fs.exists(directory) then
        fs.makeDir(directory)
    end

    local file = openFile(path, "w")
    file.write(contents)
    file.close()
end

local function inext(tbl, index)
    index = index + 1
    local value = rawget(tbl, index)
    if value ~= nil then
        return index, value
    end
end

function startModule(env)
    assertTable(env, "module environment")
    return setmetatable({}, { __index = env })
end

function endModule(env)
    assertTable(env, "module environment")

    return setmetatable({}, {
        -- rawget excludes inherited globals from the public module surface.
        __index = function(_, key)
            return rawget(env, key)
        end,
        __newindex = function(_, key, value)
            rawset(env, key, value)
        end,
        __pairs = function()
            return next, env, nil
        end,
        __ipairs = function()
            return inext, env, 0
        end
    })
end

local installerHeader = [=[
--[[ Generated by qlib.pkgr.pack. ]]
local outputDirectory = ...
local outputPath = shell.resolve(outputDirectory or "")

if fs.exists(outputPath) and not fs.isDir(outputPath) then
    error('"' .. outputPath .. '" is not a directory')
elseif not fs.exists(outputPath) then
    fs.makeDir(outputPath)
end

local files = {
]=]

local installerFooter = [=[
}

local fileCount = 0
for relativePath, contents in pairs(files) do
    local fullPath = fs.combine(outputPath, relativePath)
    local directory = fs.getDir(fullPath)
    if directory ~= "" and not fs.exists(directory) then
        fs.makeDir(directory)
    end

    local file = fs.open(fullPath, "w")
    if not file then
        error('Unable to create "' .. fullPath .. '"')
    end
    file.write(contents)
    file.close()
    fileCount = fileCount + 1
end

print("Installed " .. fileCount .. " file" .. (fileCount == 1 and "." or "s."))
]=]

function pack(inputDirectory, outputFile)
    inputDirectory = inputDirectory or ""
    assertString(outputFile, "output filepath")

    local inputPath = shell.resolve(inputDirectory)
    local outputPath = shell.resolve(outputFile)
    if not fs.exists(inputPath) then
        error('Input directory "' .. inputPath .. '" does not exist')
    elseif not fs.isDir(inputPath) then
        error('"' .. inputPath .. '" is not a directory')
    elseif fs.exists(outputPath) and fs.isDir(outputPath) then
        error('Output path "' .. outputPath .. '" is a directory')
    end

    local inputDrive = fs.getDrive(inputPath)
    local output = { installerHeader }
    local queue, head, tail, packedCount = { "" }, 1, 1, 0

    while head <= tail do
        local relativeDirectory = queue[head]
        queue[head] = nil
        head = head + 1
        local currentPath = fs.combine(inputPath, relativeDirectory)

        if fs.getDrive(currentPath) == inputDrive then
            local objects = fs.list(currentPath)
            table.sort(objects)

            for _, objectName in ipairs(objects) do
                if objectName:sub(1, 1) ~= "." then
                    local relativePath = fs.combine(relativeDirectory, objectName)
                    local absolutePath = fs.combine(inputPath, relativePath)

                    if shell.resolve(absolutePath) ~= outputPath then
                        if fs.isDir(absolutePath) then
                            if fs.getDrive(absolutePath) == inputDrive then
                                tail = tail + 1
                                queue[tail] = relativePath
                            end
                        else
                            print("Packing " .. relativePath)
                            output[#output + 1] = "    [" .. string.format("%q", relativePath) .. "] = " ..
                                string.format("%q", readFile(absolutePath)) .. ",\n"
                            packedCount = packedCount + 1
                        end
                    end
                end
            end
        end
    end

    output[#output + 1] = installerFooter
    print("Writing " .. packedCount .. " file" .. (packedCount == 1 and "" or "s") .. " to " .. outputPath .. "...")
    writeFile(outputPath, table.concat(output))
    print("Complete.")
    return true, packedCount
end

return endModule(_ENV)
